// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module SubBytes162 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_V_0,
        in_V_1,
        in_V_2,
        in_V_3,
        in_V_4,
        in_V_5,
        in_V_6,
        in_V_7,
        in_V_8,
        in_V_9,
        in_V_10,
        in_V_11,
        in_V_12,
        in_V_13,
        in_V_14,
        in_V_15,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] in_V_0;
input  [7:0] in_V_1;
input  [7:0] in_V_2;
input  [7:0] in_V_3;
input  [7:0] in_V_4;
input  [7:0] in_V_5;
input  [7:0] in_V_6;
input  [7:0] in_V_7;
input  [7:0] in_V_8;
input  [7:0] in_V_9;
input  [7:0] in_V_10;
input  [7:0] in_V_11;
input  [7:0] in_V_12;
input  [7:0] in_V_13;
input  [7:0] in_V_14;
input  [7:0] in_V_15;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;
output  [7:0] ap_return_8;
output  [7:0] ap_return_9;
output  [7:0] ap_return_10;
output  [7:0] ap_return_11;
output  [7:0] ap_return_12;
output  [7:0] ap_return_13;
output  [7:0] ap_return_14;
output  [7:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [7:0] sbox_V_address0;
reg    sbox_V_ce0;
wire   [7:0] sbox_V_q0;
wire   [7:0] sbox_V_address1;
reg    sbox_V_ce1;
wire   [7:0] sbox_V_q1;
wire   [7:0] sbox_V_address2;
reg    sbox_V_ce2;
wire   [7:0] sbox_V_q2;
wire   [7:0] sbox_V_address3;
reg    sbox_V_ce3;
wire   [7:0] sbox_V_q3;
wire   [7:0] sbox_V_address4;
reg    sbox_V_ce4;
wire   [7:0] sbox_V_q4;
wire   [7:0] sbox_V_address5;
reg    sbox_V_ce5;
wire   [7:0] sbox_V_q5;
wire   [7:0] sbox_V_address6;
reg    sbox_V_ce6;
wire   [7:0] sbox_V_q6;
wire   [7:0] sbox_V_address7;
reg    sbox_V_ce7;
wire   [7:0] sbox_V_q7;
wire   [7:0] sbox_V_address8;
reg    sbox_V_ce8;
wire   [7:0] sbox_V_q8;
wire   [7:0] sbox_V_address9;
reg    sbox_V_ce9;
wire   [7:0] sbox_V_q9;
wire   [7:0] sbox_V_address10;
reg    sbox_V_ce10;
wire   [7:0] sbox_V_q10;
wire   [7:0] sbox_V_address11;
reg    sbox_V_ce11;
wire   [7:0] sbox_V_q11;
wire   [7:0] sbox_V_address12;
reg    sbox_V_ce12;
wire   [7:0] sbox_V_q12;
wire   [7:0] sbox_V_address13;
reg    sbox_V_ce13;
wire   [7:0] sbox_V_q13;
wire   [7:0] sbox_V_address14;
reg    sbox_V_ce14;
wire   [7:0] sbox_V_q14;
wire   [7:0] sbox_V_address15;
reg    sbox_V_ce15;
wire   [7:0] sbox_V_q15;
reg    ap_block_state1;
wire   [63:0] tmp_2_fu_329_p1;
wire   [63:0] tmp_2_1_fu_334_p1;
wire   [63:0] tmp_2_2_fu_339_p1;
wire   [63:0] tmp_2_3_fu_344_p1;
wire   [63:0] tmp_2_4_fu_349_p1;
wire   [63:0] tmp_2_5_fu_354_p1;
wire   [63:0] tmp_2_6_fu_359_p1;
wire   [63:0] tmp_2_7_fu_364_p1;
wire   [63:0] tmp_2_8_fu_369_p1;
wire   [63:0] tmp_2_9_fu_374_p1;
wire   [63:0] tmp_2_s_fu_379_p1;
wire   [63:0] tmp_2_10_fu_384_p1;
wire   [63:0] tmp_2_11_fu_389_p1;
wire   [63:0] tmp_2_12_fu_394_p1;
wire   [63:0] tmp_2_13_fu_399_p1;
wire   [63:0] tmp_2_14_fu_404_p1;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

SubBytes114_sbox_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
sbox_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sbox_V_address0),
    .ce0(sbox_V_ce0),
    .q0(sbox_V_q0),
    .address1(sbox_V_address1),
    .ce1(sbox_V_ce1),
    .q1(sbox_V_q1),
    .address2(sbox_V_address2),
    .ce2(sbox_V_ce2),
    .q2(sbox_V_q2),
    .address3(sbox_V_address3),
    .ce3(sbox_V_ce3),
    .q3(sbox_V_q3),
    .address4(sbox_V_address4),
    .ce4(sbox_V_ce4),
    .q4(sbox_V_q4),
    .address5(sbox_V_address5),
    .ce5(sbox_V_ce5),
    .q5(sbox_V_q5),
    .address6(sbox_V_address6),
    .ce6(sbox_V_ce6),
    .q6(sbox_V_q6),
    .address7(sbox_V_address7),
    .ce7(sbox_V_ce7),
    .q7(sbox_V_q7),
    .address8(sbox_V_address8),
    .ce8(sbox_V_ce8),
    .q8(sbox_V_q8),
    .address9(sbox_V_address9),
    .ce9(sbox_V_ce9),
    .q9(sbox_V_q9),
    .address10(sbox_V_address10),
    .ce10(sbox_V_ce10),
    .q10(sbox_V_q10),
    .address11(sbox_V_address11),
    .ce11(sbox_V_ce11),
    .q11(sbox_V_q11),
    .address12(sbox_V_address12),
    .ce12(sbox_V_ce12),
    .q12(sbox_V_q12),
    .address13(sbox_V_address13),
    .ce13(sbox_V_ce13),
    .q13(sbox_V_q13),
    .address14(sbox_V_address14),
    .ce14(sbox_V_ce14),
    .q14(sbox_V_q14),
    .address15(sbox_V_address15),
    .ce15(sbox_V_ce15),
    .q15(sbox_V_q15)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce0 = 1'b1;
    end else begin
        sbox_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce1 = 1'b1;
    end else begin
        sbox_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce10 = 1'b1;
    end else begin
        sbox_V_ce10 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce11 = 1'b1;
    end else begin
        sbox_V_ce11 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce12 = 1'b1;
    end else begin
        sbox_V_ce12 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce13 = 1'b1;
    end else begin
        sbox_V_ce13 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce14 = 1'b1;
    end else begin
        sbox_V_ce14 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce15 = 1'b1;
    end else begin
        sbox_V_ce15 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce2 = 1'b1;
    end else begin
        sbox_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce3 = 1'b1;
    end else begin
        sbox_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce4 = 1'b1;
    end else begin
        sbox_V_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce5 = 1'b1;
    end else begin
        sbox_V_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce6 = 1'b1;
    end else begin
        sbox_V_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce7 = 1'b1;
    end else begin
        sbox_V_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce8 = 1'b1;
    end else begin
        sbox_V_ce8 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sbox_V_ce9 = 1'b1;
    end else begin
        sbox_V_ce9 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_return_0 = sbox_V_q0;

assign ap_return_1 = sbox_V_q1;

assign ap_return_10 = sbox_V_q10;

assign ap_return_11 = sbox_V_q11;

assign ap_return_12 = sbox_V_q12;

assign ap_return_13 = sbox_V_q13;

assign ap_return_14 = sbox_V_q14;

assign ap_return_15 = sbox_V_q15;

assign ap_return_2 = sbox_V_q2;

assign ap_return_3 = sbox_V_q3;

assign ap_return_4 = sbox_V_q4;

assign ap_return_5 = sbox_V_q5;

assign ap_return_6 = sbox_V_q6;

assign ap_return_7 = sbox_V_q7;

assign ap_return_8 = sbox_V_q8;

assign ap_return_9 = sbox_V_q9;

assign sbox_V_address0 = tmp_2_fu_329_p1;

assign sbox_V_address1 = tmp_2_1_fu_334_p1;

assign sbox_V_address10 = tmp_2_s_fu_379_p1;

assign sbox_V_address11 = tmp_2_10_fu_384_p1;

assign sbox_V_address12 = tmp_2_11_fu_389_p1;

assign sbox_V_address13 = tmp_2_12_fu_394_p1;

assign sbox_V_address14 = tmp_2_13_fu_399_p1;

assign sbox_V_address15 = tmp_2_14_fu_404_p1;

assign sbox_V_address2 = tmp_2_2_fu_339_p1;

assign sbox_V_address3 = tmp_2_3_fu_344_p1;

assign sbox_V_address4 = tmp_2_4_fu_349_p1;

assign sbox_V_address5 = tmp_2_5_fu_354_p1;

assign sbox_V_address6 = tmp_2_6_fu_359_p1;

assign sbox_V_address7 = tmp_2_7_fu_364_p1;

assign sbox_V_address8 = tmp_2_8_fu_369_p1;

assign sbox_V_address9 = tmp_2_9_fu_374_p1;

assign tmp_2_10_fu_384_p1 = in_V_11;

assign tmp_2_11_fu_389_p1 = in_V_12;

assign tmp_2_12_fu_394_p1 = in_V_13;

assign tmp_2_13_fu_399_p1 = in_V_14;

assign tmp_2_14_fu_404_p1 = in_V_15;

assign tmp_2_1_fu_334_p1 = in_V_1;

assign tmp_2_2_fu_339_p1 = in_V_2;

assign tmp_2_3_fu_344_p1 = in_V_3;

assign tmp_2_4_fu_349_p1 = in_V_4;

assign tmp_2_5_fu_354_p1 = in_V_5;

assign tmp_2_6_fu_359_p1 = in_V_6;

assign tmp_2_7_fu_364_p1 = in_V_7;

assign tmp_2_8_fu_369_p1 = in_V_8;

assign tmp_2_9_fu_374_p1 = in_V_9;

assign tmp_2_fu_329_p1 = in_V_0;

assign tmp_2_s_fu_379_p1 = in_V_10;

endmodule //SubBytes162
