-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MixColumns46 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_r_ce0 : OUT STD_LOGIC;
    in_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_r_ce1 : OUT STD_LOGIC;
    in_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    out_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_r_ce0 : OUT STD_LOGIC;
    out_r_we0 : OUT STD_LOGIC;
    out_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_r_ce1 : OUT STD_LOGIC;
    out_r_we1 : OUT STD_LOGIC;
    out_r_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of MixColumns46 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_1B : STD_LOGIC_VECTOR (7 downto 0) := "00011011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_7_fu_135_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_7_reg_370 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_fu_127_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_140_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_21_reg_380 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_150_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_s_reg_386 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_155_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_reg_396 : STD_LOGIC_VECTOR (4 downto 0);
    signal t_reg_401 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal in_load_reg_408 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_166_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_2_reg_415 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_fu_176_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_reg_425 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_13_fu_322_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_reg_435 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_14_fu_361_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_reg_440 : STD_LOGIC_VECTOR (7 downto 0);
    signal i1_reg_116 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_10_fu_230_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_275_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_144_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_161_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_171_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal Tm_fu_181_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_185_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_fu_203_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_i_cast_cast_ca_fu_211_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_fu_197_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tmp_fu_191_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp2_fu_224_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp1_fu_219_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_4_fu_237_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_25_fu_248_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_i20_cast_cast_s_fu_256_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_242_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp4_fu_269_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp3_fu_264_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_5_fu_282_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_27_fu_294_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_i25_cast_cast_s_fu_302_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_26_fu_288_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp6_fu_316_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp5_fu_310_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal Tm_6_fu_328_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_29_fu_339_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_333_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp7_fu_355_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_i30_cast_cast_s_fu_347_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((tmp_fu_127_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i1_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                i1_reg_116 <= i_reg_396;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i1_reg_116 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_fu_127_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                i_reg_396 <= i_fu_155_p2;
                tmp_21_reg_380 <= tmp_21_fu_140_p1;
                    tmp_7_reg_370(4 downto 0) <= tmp_7_fu_135_p1(4 downto 0);
                    tmp_s_reg_386(3 downto 1) <= tmp_s_fu_150_p1(3 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                in_load_reg_408 <= in_r_q1;
                t_reg_401 <= in_r_q0;
                    tmp_2_reg_415(0) <= tmp_2_fu_166_p1(0);    tmp_2_reg_415(3 downto 2) <= tmp_2_fu_166_p1(3 downto 2);
                    tmp_4_reg_425(3 downto 2) <= tmp_4_fu_176_p1(3 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tmp_13_reg_435 <= tmp_13_fu_322_p2;
                tmp_14_reg_440 <= tmp_14_fu_361_p2;
            end if;
        end if;
    end process;
    tmp_7_reg_370(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    tmp_s_reg_386(0) <= '1';
    tmp_s_reg_386(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    tmp_2_reg_415(1) <= '1';
    tmp_2_reg_415(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    tmp_4_reg_425(1 downto 0) <= "11";
    tmp_4_reg_425(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, tmp_fu_127_p3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((tmp_fu_127_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    Tm_4_fu_237_p2 <= (in_r_q0 xor in_load_reg_408);
    Tm_5_fu_282_p2 <= (in_r_q1 xor in_r_q0);
    Tm_6_fu_328_p2 <= (t_reg_401 xor in_r_q1);
    Tm_fu_181_p2 <= (t_reg_401 xor in_load_reg_408);
    Tmp_fu_191_p2 <= (tmp_5_fu_185_p2 xor in_r_q1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, tmp_fu_127_p3)
    begin
        if (((tmp_fu_127_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, tmp_fu_127_p3)
    begin
        if (((tmp_fu_127_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_155_p2 <= std_logic_vector(unsigned(ap_const_lv5_4) + unsigned(i1_reg_116));

    in_r_address0_assign_proc : process(tmp_7_fu_135_p1, ap_CS_fsm_state2, ap_CS_fsm_state3, tmp_2_fu_166_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_r_address0 <= tmp_2_fu_166_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            in_r_address0 <= tmp_7_fu_135_p1(4 - 1 downto 0);
        else 
            in_r_address0 <= "XXXX";
        end if; 
    end process;


    in_r_address1_assign_proc : process(ap_CS_fsm_state2, tmp_s_fu_150_p1, ap_CS_fsm_state3, tmp_4_fu_176_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_r_address1 <= tmp_4_fu_176_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            in_r_address1 <= tmp_s_fu_150_p1(4 - 1 downto 0);
        else 
            in_r_address1 <= "XXXX";
        end if; 
    end process;


    in_r_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_r_ce0 <= ap_const_logic_1;
        else 
            in_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    in_r_ce1_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            in_r_ce1 <= ap_const_logic_1;
        else 
            in_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    out_r_address0_assign_proc : process(tmp_7_reg_370, tmp_2_reg_415, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_address0 <= tmp_2_reg_415(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_r_address0 <= tmp_7_reg_370(4 - 1 downto 0);
        else 
            out_r_address0 <= "XXXX";
        end if; 
    end process;


    out_r_address1_assign_proc : process(tmp_s_reg_386, tmp_4_reg_425, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_address1 <= tmp_4_reg_425(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_r_address1 <= tmp_s_reg_386(4 - 1 downto 0);
        else 
            out_r_address1 <= "XXXX";
        end if; 
    end process;


    out_r_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_ce0 <= ap_const_logic_1;
        else 
            out_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    out_r_ce1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_ce1 <= ap_const_logic_1;
        else 
            out_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    out_r_d0_assign_proc : process(tmp_13_reg_435, ap_CS_fsm_state4, ap_CS_fsm_state5, tmp_10_fu_230_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_d0 <= tmp_13_reg_435;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_r_d0 <= tmp_10_fu_230_p2;
        else 
            out_r_d0 <= "XXXXXXXX";
        end if; 
    end process;


    out_r_d1_assign_proc : process(ap_CS_fsm_state4, tmp_14_reg_440, ap_CS_fsm_state5, tmp_12_fu_275_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            out_r_d1 <= tmp_14_reg_440;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_r_d1 <= tmp_12_fu_275_p2;
        else 
            out_r_d1 <= "XXXXXXXX";
        end if; 
    end process;


    out_r_we0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_we0 <= ap_const_logic_1;
        else 
            out_r_we0 <= ap_const_logic_0;
        end if; 
    end process;


    out_r_we1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_we1 <= ap_const_logic_1;
        else 
            out_r_we1 <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_219_p2 <= (tmp_2_i_cast_cast_ca_fu_211_p3 xor t_reg_401);
    tmp2_fu_224_p2 <= (tmp_22_fu_197_p2 xor Tmp_fu_191_p2);
    tmp3_fu_264_p2 <= (tmp_2_i20_cast_cast_s_fu_256_p3 xor in_load_reg_408);
    tmp4_fu_269_p2 <= (tmp_24_fu_242_p2 xor Tmp_fu_191_p2);
    tmp5_fu_310_p2 <= (tmp_2_i25_cast_cast_s_fu_302_p3 xor in_r_q0);
    tmp6_fu_316_p2 <= (tmp_26_fu_288_p2 xor Tmp_fu_191_p2);
    tmp7_fu_355_p2 <= (tmp_5_fu_185_p2 xor tmp_28_fu_333_p2);
    tmp_10_fu_230_p2 <= (tmp2_fu_224_p2 xor tmp1_fu_219_p2);
    tmp_12_fu_275_p2 <= (tmp4_fu_269_p2 xor tmp3_fu_264_p2);
    tmp_13_fu_322_p2 <= (tmp6_fu_316_p2 xor tmp5_fu_310_p2);
    tmp_14_fu_361_p2 <= (tmp_2_i30_cast_cast_s_fu_347_p3 xor tmp7_fu_355_p2);
    tmp_1_fu_161_p2 <= (tmp_21_reg_380 or ap_const_lv4_2);
    tmp_21_fu_140_p1 <= i1_reg_116(4 - 1 downto 0);
    tmp_22_fu_197_p2 <= std_logic_vector(shift_left(unsigned(Tm_fu_181_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    tmp_23_fu_203_p3 <= Tm_fu_181_p2(7 downto 7);
    tmp_24_fu_242_p2 <= std_logic_vector(shift_left(unsigned(Tm_4_fu_237_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    tmp_25_fu_248_p3 <= Tm_4_fu_237_p2(7 downto 7);
    tmp_26_fu_288_p2 <= std_logic_vector(shift_left(unsigned(Tm_5_fu_282_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    tmp_27_fu_294_p3 <= Tm_5_fu_282_p2(7 downto 7);
    tmp_28_fu_333_p2 <= std_logic_vector(shift_left(unsigned(Tm_6_fu_328_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    tmp_29_fu_339_p3 <= Tm_6_fu_328_p2(7 downto 7);
    tmp_2_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_161_p2),64));
    tmp_2_i20_cast_cast_s_fu_256_p3 <= 
        ap_const_lv8_1B when (tmp_25_fu_248_p3(0) = '1') else 
        ap_const_lv8_0;
    tmp_2_i25_cast_cast_s_fu_302_p3 <= 
        ap_const_lv8_1B when (tmp_27_fu_294_p3(0) = '1') else 
        ap_const_lv8_0;
    tmp_2_i30_cast_cast_s_fu_347_p3 <= 
        ap_const_lv8_1B when (tmp_29_fu_339_p3(0) = '1') else 
        ap_const_lv8_0;
    tmp_2_i_cast_cast_ca_fu_211_p3 <= 
        ap_const_lv8_1B when (tmp_23_fu_203_p3(0) = '1') else 
        ap_const_lv8_0;
    tmp_3_fu_171_p2 <= (tmp_21_reg_380 or ap_const_lv4_3);
    tmp_4_fu_176_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_171_p2),64));
    tmp_5_fu_185_p2 <= (in_r_q0 xor Tm_fu_181_p2);
    tmp_7_fu_135_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i1_reg_116),64));
    tmp_9_fu_144_p2 <= (tmp_21_fu_140_p1 or ap_const_lv4_1);
    tmp_fu_127_p3 <= i1_reg_116(4 downto 4);
    tmp_s_fu_150_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_144_p2),64));
end behav;
